#some of the "valid" int'l codes were commented out because tor/stem doesn't recognize them...
digraphs = {
"??":"**unknown**",
"00":"**unknown**",
"a1":"**anonymous proxy**",
"a2":"**satellite provider**",
#"ac":"Ascension Island",
"ad":"Andorra",
"ae":"United Arab Emirates",
"af":"Afghanistan",
"ag":"Antigua and Barbuda",
"ai":"Anguilla",
#"ak":"Aitutaki",
"al":"Albania",
"am":"Armenia",
"an":"Netherlands Antilles",
"ao":"Angola",
"ap":"Asia-Pacific (unknown)",
"aq":"Antarctica",
"ar":"Argentina",
"as":"American Samoa",
"at":"Austria",
"au":"Australia",
"aw":"Aruba",
"ax":"Aland Islands",
#"ay":"Alderney",
"az":"Azerbaijan",
"ba":"Bosnia-Herzegovina",
"bb":"Barbados",
"bd":"Bangladesh",
"be":"Belgium",
"bf":"Burkina Faso",
"bg":"Bulgaria",
"bh":"Bahrain",
"bi":"Burundi",
"bj":"Benin",
#"bl":"Saint Barthelemy",
"bm":"Bermuda",
"bn":"Brunei",
"bo":"Bolivia",
#"bq":"Bonaire, Sint Eustatius and Saba",
"br":"Brazil",
"bs":"Bahamas",
"bt":"Bhutan",
#"bu":"British Antarctic Territory",
"bv":"Bouvet Island",
"bw":"Botswana",
#"bx":"Bophuthatswana",
"by":"Belarus",
"bz":"Belize",
"ca":"Canada",
"cc":"Cocos Islands",
"cd":"Congo, The Democratic Republic of",
#"ce":"Ciskei",
"cf":"Central African Republic",
"cg":"Congo",
"ch":"Switzerland",
"ci":"Ivory Coast",
"ck":"Cook Islands",
"cl":"Chile",
"cm":"Cameroon",
"cn":"China",
"co":"Colombia",
"cr":"Costa Rica",
#"cs":"Czechoslovakia (former)",
"cu":"Cuba",
"cv":"Cape Verde",
#"cw":"Curacao",
"cx":"Christmas Island",
"cy":"Cyprus",
"cz":"Czech Republic",
#"dd":"German Democratic Republic",
"de":"Germany",
"dj":"Djibouti",
"dk":"Denmark",
"dm":"Dominica",
"do":"Dominican Republic",
"dz":"Algeria",
"ec":"Ecuador",
"ee":"Estonia",
"eg":"Egypt",
"eh":"Western Sahara",
"er":"Eritrea",
"es":"Spain",
"et":"Ethiopia",
"eu":"European Union (unknown)",
"fi":"Finland",
"fj":"Fiji",
"fk":"Falkland Islands",
"fm":"Micronesia",
"fo":"Faroe Islands",
"fr":"France",
#"fx":"Metropolitan France",
"ga":"Gabon",
"gb":"United Kingdom",
"gd":"Grenada",
"ge":"Georgia",
"gf":"French Guiana",
"gg":"Guernsey",
"gh":"Ghana",
"gi":"Gibraltar",
"gl":"Greenland",
"gm":"Gambia",
"gn":"Guinea",
"gp":"Guadaloupe",
"gq":"Equatorial Guinea",
"gr":"Greece",
"gs":"South Georgia",
"gt":"Guatemala",
"gu":"Guam",
"gw":"Guinea-Bissau",
#"gx":"Guernsey",
"gy":"Guyana",
"hk":"Hong Kong",
#"hm":"Heard and McDonald Islands",
"hn":"Honduras",
"hr":"Croatia",
"ht":"Haiti",
"hu":"Hungary",
"id":"Indonesia",
"ie":"Ireland",
"il":"Israel",
"im":"Isle of Man",
"in":"India",
"io":"British Indian Ocean Territory",
"iq":"Iraq",
"ir":"Iran",
"is":"Iceland",
"it":"Italy",
"je":"Bailiwick of Jersey",
"jm":"Jamaica",
"jo":"Jordan",
"jp":"Japan",
#"jy":"Jersey",
"ke":"Kenya",
"kg":"Kyrgyzstan",
"kh":"Cambodia",
"ki":"Kiribati",
"km":"Comoros",
"kn":"Saint Kitts and Nevis",
"kp":"Korea (North)",
"kr":"Korea",
"kw":"Kuwait",
"ky":"Cayman Islands",
"kz":"Kazakhstan",
"la":"Laos",
"lb":"Lebanon",
"lc":"Saint Lucia",
"li":"Liechtenstein",
"lk":"Sri Lanka",
"lr":"Liberia",
"ls":"Lesotho",
"lt":"Lithuania",
"lu":"Luxembourg",
"lv":"Latvia",
"ly":"Libya",
"ma":"Morocco",
"mc":"Monaco",
"md":"Moldova",
"me":"Montenegro",
#"mf":"Saint Martin",
"mg":"Madagascar",
"mh":"Marshall Islands",
"mk":"Macedonia",
"ml":"Mali",
"mm":"Myanmar",
"mn":"Mongolia",
"mo":"Macau",
"mp":"Northern Mariana Islands",
"mq":"Martinique",
"mr":"Mauritania",
"ms":"Montserrat",
"mt":"Malta",
"mu":"Mauritius",
"mv":"Maldives",
"mw":"Malawi",
"mx":"Mexico",
"my":"Malaysia",
"mz":"Mozambique",
"na":"Namibia",
"nc":"New Caledonia",
"ne":"Niger",
"nf":"Norfolk Island",
"ng":"Nigeria",
"ni":"Nicaragua",
"nl":"Netherlands",
"no":"Norway",
"np":"Nepal",
"nr":"Nauru",
"nu":"Niue",
#"nv":"Nevis",
"nz":"New Zealand",
"om":"Oman",
"pa":"Panama",
"pe":"Peru",
"pf":"French Polynesia",
"pg":"Papua New Guinea",
"ph":"Philippines",
"pk":"Pakistan",
"pl":"Poland",
"pm":"Saint Pierre et Miquelon",
#"pn":"Pitcairn Islands",
"pr":"Puerto Rico",
"ps":"Palestine",
"pt":"Portugal",
"pw":"Palau",
#"px":"Penrhyn",
"py":"Paraguay",
"qa":"Qatar",
"re":"Reunion",
"ro":"Romania",
"rs":"Serbia",
"ru":"Russia",
"rw":"Rwanda",
"sa":"Saudi Arabia",
"sb":"Solomon Islands",
"sc":"Seychelles",
"sd":"Sudan",
"se":"Sweden",
"sg":"Singapore",
"sh":"Saint Helena",
"si":"Slovenia",
"sj":"Svalbard og Jan Mayen",
"sk":"Slovakia",
"sl":"Sierra Leone",
"sm":"San Marino",
"sn":"Senegal",
"so":"Somalia",
"sr":"Suriname",
#"ss":"South Sudan",
"st":"Sao Tome e Principe",
#"su":"USSR",
"sv":"El Salvador",
#"sw":"South West Africa",
#"sx":"St. Kitts",
"sy":"Syria",
"sz":"Swaziland",
"tc":"Turks and Caicos",
"td":"Chad",
"tf":"French Southern Territories",
"tg":"Togo",
"th":"Thailand",
"tj":"Tajikistan",
"tk":"Tokelau",
"tl":"Timor-Leste",
"tm":"Turkmenistan",
"tn":"Tunisia",
"to":"Tonga",
#"tp":"Timor",
"tr":"Turkey",
"tt":"Trinidad and Tobago",
"tv":"Tuvalu",
"tw":"Taiwan",
#"tx":"Tristan da Chuna",
"tz":"Tanzania",
"ua":"Ukraine",
"ug":"Uganda",
"um":"US Minor Outlying Islands",
#"un":"U.N. (New York)",
"us":"U.S.",
#"uu":"U.N. (Geneva)",
#"uv":"U.N. (Vienna)",
#"ux":"U.N. (All Offices)",
"uy":"Uruguay",
"uz":"Uzbekistan",
"va":"Vatican",
"vc":"Saint Vincent and Grenadines",
"ve":"Venezuela",
"vg":"British Virgin Islands",
"vi":"US Virgin Islands",
"vn":"Vietnam",
"vu":"Vanuatu",
"wf":"Wallis et Futuna",
"ws":"Samoa",
"ye":"Yemen",
"yt":"Mayotte",
#"yu":"Yugoslavia",
"za":"South Africa",
"zm":"Zambia",
#"zr":"Zaire",
"zw":"Zimbabwe",
}
